"Vui lòng xác nhận bạn không phải là người máy",
"Mật khẩu nhập lại không khớp",
"Không thể liên hệ CAPTCHA. Hãy kiểm tra kết nối và thử lại",
"Tên đăng nhập đã tồn tại",
"Phiên CAPTCHA đã hết hạn, vui lòng xác nhận lại và tiếp tục",
"Tên nhân vật đã tồn tại",
"Bạn đã đăng ký thành công",
"Tên nhân vật không tồn tại",
"Mật khẩu không đúng",
